logging:
  log_file: "picota/picota.log"
  level: "INFO"





delete_fastq_files: true
sra_id_file: "picota/selected_sra.csv"

outdir : "/media/lin-bio/back2/picota_project_longTestIS26"


path_of_fastq_dump: "parallel-fastq-dump"
assembly_threads: 24
assembly_k_mer_list: "79,99"
assembly_quiet: true
assembly_keep_temp_files: true
assembly_path_of_spades: "spades.py"
assembly_path_of_fastp: "fastp"
assembly_skip_filtering: true
assembler_type: "megahit"
assembly_path_of_megahit: "megahit"

gfa_tools_path: "./picota/tools/gfaview/misc/fastg2gfa"
path_of_bandage: "./picota/tools/Bandage_Ubuntu-x86-64_v0.9.0_AppDir/Bandage_Ubuntu-x86-64_v0.9.0/usr/bin/bandage"

path_to_antibiotics: "picota/DBs/Antibiotics/protein_fasta_protein_homolog_model.fasta"
path_to_xenobiotics: "picota/DBs/Xenobiotics/Xenobiotics_classified.fasta"
path_to_ises: "picota/DBs/ISes/tncentral_integrall_isfinder.fa"

find_all_path: true
path_limit: 25
min_size_of_cycle: 2000
max_size_of_cycle: 50000
name_prefix_cycle: "Cycle"
min_component_number: 1
max_component_number: 50
k_mer_sim: 50
threshold_sim: 50

mapping_threads: 8




block_patterns:
  CT: ["cargo", "transposon"]
  TC: ["transposon", "cargo"]
  TCT: ["transposon", "cargo", "transposon"]
  CTC: ["cargo", "transposon", "cargo"]
  CTCT: ["cargo", "transposon", "cargo", "transposon"]
  TCTC: ["transposon", "cargo", "transposon", "cargo"]
  TCTCT: ["transposon", "cargo", "transposon", "cargo", "transposon"]
  CTCTC: ["cargo", "transposon", "cargo", "transposon", "cargo"]
  TCTCTC: ["transposon", "cargo", "transposon", "cargo", "transposon", "cargo"]
  TCTCTCT: ["transposon", "cargo", "transposon", "cargo", "transposon", "cargo", "transposon"]

block_tolerances:
  tolerance: 1000
  small_overlap: 300
  boosted_tolerance: 1000
  max_boost: 5000
  mode_gap_tolerance: 200
  min_large_fraction: 0.25
  absolute_small_gap: 200

block_plotting:
  outdir: "figures"
  prefix: "global"
  hist_bins: 30
  scatter_point_size: 30
  scatter_alpha: 0.6
