# -------------------------
# Logging
# -------------------------
logging:
  log_file: "/media/lin-bio/back2/picota_project_BIOMIGTest/picota.log"
  level: "DEBUG"
  logger_name: "picota_analysis"

# -------------------------
# Paths / General pipeline settings
# -------------------------
paths:
  # Pipeline
  outdir: "/media/lin-bio/back2/picota_project_BIOMIGTest"
  sra_id_file: "picota/sra_ids.tsv"
  fastq_dump: "parallel-fastq-dump"

  # Assembly
  assembly_threads: 24
  assembly_k_mer_list: "99"
  quiet: true
  keep_temp_files: true
  path_of_spades: "spades.py"
  path_of_fastp: "fastp"
  skip_filtering: true
  #assembler_type: "megahit"
  assembler_type: "spades"
  path_of_megahit: "megahit"

  # Tools
  gfa_tools_path: "./picota/tools/gfaview/misc/fastg2gfa"
  path_of_bandage: "./picota/tools/Bandage_Ubuntu-x86-64_v0.9.0_AppDir/Bandage_Ubuntu-x86-64_v0.9.0/usr/bin/bandage"

  # Databases
  path_to_antibiotics: "picota/DBs/Antibiotics/protein_fasta_protein_homolog_model.fasta"
  path_to_xenobiotics: "picota/DBs/Xenobiotics/Xenobiotics_classified.fasta"
  path_to_ises: "picota/DBs/ISes/tncentral_integrall_isfinder.fa"

  # SRA
  find_all_path: true
  path_limit: 25

# -------------------------
# General options
# -------------------------
options:
  delete_fastq_files: true
  min_size_of_cycle: 2000
  max_size_of_cycle: 30000
  name_prefix_cycle: "Cycle"
  min_component_number: 1
  max_component_number: 25
  k_mer_sim: 80
  threshold_sim: 80
  mapping_threads: 8
  split_min_score: 101


# new parameters
  mean_of_CompTns: 5850
  std_of_CompTns: 2586
  total_score_type: 0
  threshold_final_score: 50
  max_z: 20
  dist_type: 1
  path_of_prodigal: "prodigal"
  path_of_blastn: "blastn"
  path_of_makeblastdb: "makeblastdb"
  path_of_blastx: "blastx"
  path_of_blastp: "blastp"




# -------------------------
# Block patterns
# -------------------------
patterns:
  CT: ["cargo", "transposon"]
  TC: ["transposon", "cargo"]
  TCT: ["transposon", "cargo", "transposon"]
  CTC: ["cargo", "transposon", "cargo"]
  CTCT: ["cargo", "transposon", "cargo", "transposon"]
  TCTC: ["transposon", "cargo", "transposon", "cargo"]
  TCTCT: ["transposon", "cargo", "transposon", "cargo", "transposon"]
  CTCTC: ["cargo", "transposon", "cargo", "transposon", "cargo"]
  TCTCTC: ["transposon", "cargo", "transposon", "cargo", "transposon", "cargo"]
  TCTCTCT: ["transposon", "cargo", "transposon", "cargo", "transposon", "cargo", "transposon"]

# -------------------------
# Block tolerances
# -------------------------
tolerances:
  tolerance: 1000
  small_overlap: 300
  boosted_tolerance: 1000
  max_boost: 5000
  mode_gap_tolerance: 200
  min_large_fraction: 0.25
  absolute_small_gap: 200
  max_reasonable_gap: 10000  

# -------------------------
# Plotting config
# -------------------------
plotting:
  outdir: "figures"
  prefix: "global"
  hist_bins: 30
  scatter_point_size: 30
  scatter_alpha: 0.6
